# Generated by Django 4.2.7 on 2023-11-08 16:44

import apps.profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Address"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Company Description"
            ),
        ),
        migrations.AddField(
            model_name="rep",
            name="address_line_1",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Address Line 1"
            ),
        ),
        migrations.AddField(
            model_name="rep",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Address Line 2"
            ),
        ),
        migrations.AddField(
            model_name="rep",
            name="alternative_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="rep",
            name="city",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="rep",
            name="country",
            field=django_countries.fields.CountryField(
                default="GH", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="rep",
            name="employed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rep",
            name="employer",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="rep",
            name="employer_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="rep",
            name="employer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="rep",
            name="employer_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="rep",
            name="home_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="rep",
            name="id_card",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.profiles.models.Rep.user_directory_path,
            ),
        ),
        migrations.AddField(
            model_name="rep",
            name="mobile_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="rep",
            name="postal_code",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="rep",
            name="region",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="rep",
            name="second_nationality",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="First Nationality"
            ),
        ),
        migrations.AddField(
            model_name="rep",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rep",
            name="work_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="first_nationality",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="First Nationality"
            ),
        ),
    ]
