# Generated by Django 4.2.7 on 2023-11-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_contactperson_company_about_company_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rep",
            name="date_of_birth",
            field=models.DateField(auto_now=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="rep",
            name="maritial_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                ],
                default="Single",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Place of Birth"
            ),
        ),
    ]
