# Generated by Django 4.2.7 on 2023-11-09 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0003_alter_rep_date_of_birth_alter_rep_maritial_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.category",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=django_countries.fields.CountryField(
                default="GH", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="name",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Company Name"
            ),
        ),
        migrations.AddField(
            model_name="contactperson",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
