# Generated by Django 4.2.7 on 2023-11-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_company_registration_date_company_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactperson",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="contact_people", to="profiles.company"
            ),
        ),
    ]
