# Generated by Django 4.2.7 on 2023-11-13 17:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_contactperson_companies"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
