# Generated by Django 4.2.7 on 2023-11-14 09:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_rename_name_company_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="email",
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=30, region=None
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="employer_email",
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="rep",
            name="employer_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=30, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="home_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=30, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="mobile_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=30, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="work_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=30, null=True, region=None
            ),
        ),
    ]
