# Generated by Django 4.2.7 on 2023-11-14 10:20

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_alter_company_email_alter_contactperson_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="GH", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "company",
                    models.ManyToManyField(
                        blank=True, related_name="Countries", to="profiles.company"
                    ),
                ),
            ],
        ),
    ]
