# Generated by Django 4.2.7 on 2023-11-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="country",
        ),
    ]
