# Generated by Django 4.2.7 on 2023-11-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_remove_company_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="company",
            new_name="companies",
        ),
    ]
