# Generated by Django 4.2.7 on 2023-11-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_rename_company_country_companies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="country",
            new_name="operating_country",
        ),
    ]
