# Generated by Django 4.2.7 on 2023-11-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_rename_country_country_operating_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="operating_country",
            new_name="country",
        ),
    ]
