# Generated by Django 4.2.7 on 2023-11-14 16:16

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_rename_operating_country_country_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="companies",
        ),
        migrations.AddField(
            model_name="company",
            name="countries",
            field=django_countries.fields.CountryField(
                default="GH", max_length=2, verbose_name="Country"
            ),
        ),
    ]
