# Generated by Django 4.2.7 on 2023-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_name_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("Company", "Company"), ("Rep", "Rep")],
                default="n/a",
                max_length=50,
                verbose_name="User Type",
            ),
        ),
    ]
