# Generated by Django 4.2.7 on 2023-11-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("COMPANY", "Company"), ("REP", "Rep")],
                default="n/a",
                max_length=50,
                verbose_name="User Type",
            ),
        ),
    ]
