# Generated by Django 4.2.7 on 2023-11-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_code",
            field=models.CharField(default="n/a", max_length=20),
        ),
    ]
