# Generated by Django 4.2.7 on 2023-11-14 09:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_registration_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=30,
                null=True,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
