# Generated by Django 4.2.7 on 2023-11-14 16:28

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_productimage_remove_product_image1_product_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="web_id",
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True
            ),
        ),
    ]
